name: .NET Core

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
    
env:
  SOLUTION_PATH: "src/Trakx.Utils.sln"
  
jobs: 
  build:
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore ${{env.SOLUTION_PATH}}
    - name: Build
      run: |
        dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
        dotnet build ${{env.SOLUTION_PATH}} --configuration Debug --no-restore

    - name: Test & Coverage
      run: |
        for f in ./src/*.Tests/*.Tests.csproj; do echo "testing project $f" && \
        dotnet test $f --configuration Debug --no-restore \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=opencover \
            /p:UserSourceLink=true \
            /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\" \
            /p:Include=\"[Trakx.*]*\"; \
        done
        #dotnet test ${{env.SOLUTION_PATH}} --no-restore --logger GitHubActions --verbosity normal
    - name: Publish Coverage
      uses: codacy/codacy-coverage-reporter-action@master
      with:
        project-token: ${{ secrets.CODACY_TOKEN }}
        coverage-reports: ./src/Trakx.Utils.Tests/coverage.opencover.xml
